// Agent Swarm Registry with Human Persona Attributes (Male & Female Employees)
const SWARM_AGENTS = [
  {
    id: 'aero-writer',
    name: 'Maya',
    title: 'Lead SEO & Tech Copywriter',
    gender: 'female',
    role: 'SEO Content Engine',
    avatar: '👩‍💼',
    color: '#00f0ff',
    deskPos: { x: 180, y: 220 },
    chairPos: { x: 180, y: 260 },
    pantryPos: { x: 800, y: 150 },
    whiteboardPos: { x: 480, y: 140 },
    engine: 'Claude (real) + Google Search Console rank data',
    currentTask: 'Syncing status...',
    target: 'Rank #1 untuk semua tracked keyword (lihat data real via sync)',
    state: 'WORKING', // WORKING, WALKING, COFFEE, WHITEBOARD
    lastLog: 'Syncing status dari tepatlaser.com...',
    actionLabel: 'GENERATE NEW BLOG NOW',
    appearance: {
      hairStyle: 'bob',
      hairColor: '#1e293b',
      skinColor: '#fcd34d',
      shirtColor: '#06b6d4',
      pantsColor: '#1e293b',
      accessory: 'glasses'
    }
  },
  {
    id: 'hermes-sentry',
    name: 'Budi',
    title: 'Customer Success & Lead Ops',
    gender: 'male',
    role: 'Lead & WA Dispatcher',
    avatar: '👨‍💼',
    color: '#00ff66',
    deskPos: { x: 380, y: 220 },
    chairPos: { x: 380, y: 260 },
    pantryPos: { x: 820, y: 150 },
    whiteboardPos: { x: 520, y: 140 },
    engine: 'FastAPI Microservice + Telegram Bot API',
    currentTask: 'Standby menerima pesan WA calon pembeli & forward ke Telegram',
    target: 'WhatsApp Number 0821-2129-2937',
    state: 'WORKING',
    lastLog: '📡 Hermes Webhook active on port 8765. SQLite leads.db initialized.',
    actionLabel: 'INSPECT RECENT LEADS',
    appearance: {
      hairStyle: 'short',
      hairColor: '#451a03',
      skinColor: '#fed7aa',
      shirtColor: '#22c55e',
      pantsColor: '#334155',
      accessory: 'headset'
    }
  },
  {
    id: 'radar-x',
    name: 'Nadia',
    title: 'SEO Intelligence Agent',
    gender: 'female',
    role: 'Paid Waste to Organic Opportunity',
    avatar: '👩‍💻',
    color: '#ffe600',
    deskPos: { x: 580, y: 220 },
    chairPos: { x: 580, y: 260 },
    pantryPos: { x: 840, y: 150 },
    whiteboardPos: { x: 440, y: 140 },
    engine: 'Deterministic SEO Rule Engine + Provider Abstractions',
    currentTask: 'Analyze paid search demand into evidence-backed SEO opportunities',
    target: 'Google Ads + GSC provenance, clustering, scoring, and proposed Maya tasks',
    state: 'IDLE',
    lastLog: 'No analysis status loaded yet. Open Nadia to fetch persisted backend state.',
    actionLabel: 'RUN NADIA ANALYSIS',
    appearance: {
      hairStyle: 'ponytail',
      hairColor: '#78350f',
      skinColor: '#fed7aa',
      shirtColor: '#eab308',
      pantsColor: '#0f172a',
      accessory: 'glasses'
    }
  },
  {
    id: 'iron-shield',
    name: 'Rian',
    title: 'PPC Architect & Budget Auditor',
    gender: 'male',
    role: 'Ad Budget Optimizer',
    avatar: '👨‍💻',
    color: '#ff0055',
    deskPos: { x: 280, y: 380 },
    chairPos: { x: 280, y: 420 },
    pantryPos: { x: 800, y: 180 },
    whiteboardPos: { x: 500, y: 140 },
    engine: 'Search Terms Analyzer & Negative Keyword Generator',
    currentTask: 'Blokir 1.909 keyword boncos di Google Ads agar hemat budget',
    target: 'Google Ads Campaign #1038592',
    state: 'WORKING',
    lastLog: '🛡️ Generated negative keyword list for 102 organic pages to prevent ad cannibalization.',
    actionLabel: 'SYNC NEGATIVE KEYWORDS',
    appearance: {
      hairStyle: 'undercut',
      hairColor: '#0f172a',
      skinColor: '#fde047',
      shirtColor: '#f43f5e',
      pantsColor: '#1e293b',
      accessory: 'watch'
    }
  },
  {
    id: 'cloud-forge',
    name: 'Gilang',
    title: 'DevOps & Server Architect',
    gender: 'male',
    role: 'CI/CD Cloud Deployer',
    avatar: '👨‍🔧',
    color: '#9d4edd',
    deskPos: { x: 480, y: 380 },
    chairPos: { x: 480, y: 420 },
    pantryPos: { x: 830, y: 180 },
    whiteboardPos: { x: 460, y: 140 },
    engine: 'GitHub Actions Cloud Runner + Hostinger FTP + Cloudflare API',
    currentTask: 'Auto-build 104 halaman HTML ke Hostinger & purge Cloudflare',
    target: 'tepatlaser.com (Hostinger FTP 103.185.53.100)',
    state: 'WORKING',
    lastLog: '🚀 Workflow daily-publish.yml scheduled (0 0 * * * UTC). Cloud purge verified.',
    actionLabel: 'TRIGGER CLOUD PURGE',
    appearance: {
      hairStyle: 'cap',
      hairColor: '#a855f7',
      skinColor: '#fed7aa',
      shirtColor: '#8b5cf6',
      pantsColor: '#1e1e24',
      accessory: 'headphones'
    }
  }
];
