(function(){
 const authHeaders=()=>({'Authorization':`Bearer ${localStorage.getItem('hq_auth_token')||''}`,'Content-Type':'application/json'});
 async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...authHeaders(),...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||`HTTP ${r.status}`);return data;}
 const rupiah=(n)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
 const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function stageBadge(stage){return `<span class="pmo-stage pmo-stage-${String(stage).toLowerCase()}">${esc(stage)}</span>`;}
 async function refresh(){try{const [d,p,i,h]=await Promise.all([api('/api/pmo/dashboard'),api('/api/pmo/projects?limit=30'),api('/api/pmo/inbox?status=NEW&limit=15'),api('/api/pmo/integrations/health')]);renderKpi(d);renderProjects(p.projects||[]);renderAttention(d.dashboard||{});renderInbox(i.inbox||[]);renderHealth(h.integrations||{});}catch(e){const root=document.getElementById('pmo-kpi-grid');if(root)root.innerHTML=`<div class="pmo-card pmo-error">${esc(e.message)}</div>`;}}
 function renderKpi(data){const d=data.dashboard||{},k=data.kpis||{},cards=[['PROJECTS',d.projects?.total||0],['PENDING APPROVAL',d.attention?.pendingApprovals||0],['BLOCKED TASK',d.attention?.blockedTasks||0],['RECEIVABLE',rupiah(d.finance?.receivable||0)],['WIN RATE',`${k.winRate||0}%`],['GROSS MARGIN',rupiah(k.grossMargin||0)]];document.getElementById('pmo-kpi-grid').innerHTML=cards.map(([a,b])=>`<div class="pmo-kpi"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('');}
 function renderProjects(projects){document.getElementById('pmo-project-list').innerHTML=projects.length?projects.map(p=>`<button class="pmo-project-row" onclick="window.pmoInspectProject('${esc(p.id)}')"><span><b>${esc(p.code)}</b> ${esc(p.title)}</span>${stageBadge(p.stage)}<small>${esc(p.clientName||p.client_name||'-')} · ${rupiah(p.contractValue||p.contract_value||0)}</small></button>`).join(''):'<div class="loading-state">Belum ada project.</div>';}
 function renderAttention(d){const risks=(d.attention?.openRisks||[]).map(x=>`${x.severity}: ${x.count}`).join(' · ')||'0';const due=(d.attention?.dueProjects||[]).slice(0,5).map(x=>`<div class="pmo-attention"><b>${esc(x.code)}</b> ${esc(x.title)}<small>Due ${esc(x.due_date||'-')}</small></div>`).join('');document.getElementById('pmo-attention-list').innerHTML=`<div class="pmo-attention"><b>Pending approval</b><strong>${d.attention?.pendingApprovals||0}</strong></div><div class="pmo-attention"><b>Open risk</b><span>${esc(risks)}</span></div>${due||'<div class="loading-state">Tidak ada due project.</div>'}`;}
 function renderInbox(items){document.getElementById('pmo-inbox-list').innerHTML=items.length?items.map(x=>`<div class="pmo-inbox-row"><b>${esc(x.contact_name||x.phone)}</b><span>${esc(x.classification||'GENERAL')} · ${esc(x.summary||'')}</span><button onclick="window.pmoPromoteInbox('${esc(x.id)}')">PROMOTE</button></div>`).join(''):'<div class="loading-state">Inbox bersih.</div>';}
 function renderHealth(h){document.getElementById('pmo-health').innerHTML=`<div class="pmo-health-row"><b>WhatsApp Gateway</b><span class="${h.whatsapp?.ok?'text-green':'text-yellow'}">${h.whatsapp?.ok?'ONLINE':h.whatsapp?.configured?'DEGRADED':'NOT CONFIGURED'}</span></div><div class="pmo-health-row"><b>n8n</b><span>${h.n8n?.configured?'CONFIGURED':'NOT CONFIGURED'}</span></div>`;}
 async function inspectProject(id){const d=await api(`/api/pmo/projects/${encodeURIComponent(id)}`);const r=d.report;alert(`${r.project.code} — ${r.project.title}\nStage: ${r.project.stage}\nHealth: ${r.health.status} (${r.health.score})\nOutstanding: ${rupiah(r.finance.outstanding)}\nBlocked: ${r.planning.blockedTasks}`);}
 async function promoteInbox(id){const title=prompt('Nama project / pekerjaan:');if(!title)return;await api(`/api/pmo/inbox/${encodeURIComponent(id)}/promote`,{method:'POST',body:JSON.stringify({title})});await refresh();}
 async function openNewProject(){const title=prompt('Nama project kontraktor:');if(!title)return;const clientName=prompt('Nama customer:')||'';const clientPhone=prompt('Nomor WhatsApp:')||'';await api('/api/pmo/projects',{method:'POST',body:JSON.stringify({title,clientName,clientPhone,source:'MANUAL'})});await refresh();}
 window.pmoRefresh=refresh;window.pmoInspectProject=inspectProject;window.pmoPromoteInbox=promoteInbox;window.pmoOpenNewProject=openNewProject;
})();
