import { sendJson,readJson,actorFromSession,handleError,routeMatch } from './helpers.mjs';
export async function handleProjectRoutes(req,res,{path,url,platform,session}){try{
 if(path==='/api/pmo/projects'&&req.method==='GET'){const projects=platform.projects.list({stage:url.searchParams.get('stage')||null,search:url.searchParams.get('q')||null,limit:url.searchParams.get('limit')||100});sendJson(res,200,{status:'success',count:projects.length,projects});return true;}
 if(path==='/api/pmo/projects'&&req.method==='POST'){const body=await readJson(req);const project=platform.projects.create(body,{actor:actorFromSession(session)});sendJson(res,201,{status:'success',project});return true;}
 let m=routeMatch(path,/^\/api\/pmo\/projects\/([^/]+)$/);if(m&&req.method==='GET'){const project=platform.projects.get(m[0]);if(!project)return sendJson(res,404,{status:'error',message:'PROJECT_NOT_FOUND'}),true;const report=platform.reports.project(project.id);sendJson(res,200,{status:'success',project,report});return true;}
 m=routeMatch(path,/^\/api\/pmo\/projects\/([^/]+)$/);if(m&&req.method==='PATCH'){const project=platform.projects.update(m[0],await readJson(req),{actor:actorFromSession(session)});sendJson(res,200,{status:'success',project});return true;}
 m=routeMatch(path,/^\/api\/pmo\/projects\/([^/]+)\/transition$/);if(m&&req.method==='POST'){const body=await readJson(req);const project=platform.projects.get(m[0]);if(!project)return sendJson(res,404,{status:'error',message:'PROJECT_NOT_FOUND'}),true;platform.stageGates.assert(project.id,body.toStage);const out=platform.projects.transition(project.id,body.toStage,{actor:actorFromSession(session),note:body.note,force:Boolean(body.force)});sendJson(res,200,{status:'success',project:out});return true;}
 m=routeMatch(path,/^\/api\/pmo\/projects\/([^/]+)\/milestones$/);if(m&&req.method==='POST'){sendJson(res,201,{status:'success',milestone:platform.planning.addMilestone(m[0],await readJson(req))});return true;}
 m=routeMatch(path,/^\/api\/pmo\/projects\/([^/]+)\/tasks$/);if(m&&req.method==='POST'){sendJson(res,201,{status:'success',task:platform.planning.addTask(m[0],await readJson(req))});return true;}
 m=routeMatch(path,/^\/api\/pmo\/tasks\/([^/]+)\/status$/);if(m&&req.method==='POST'){const b=await readJson(req);sendJson(res,200,{status:'success',task:platform.planning.setTaskStatus(m[0],b.status,{progress:b.progress})});return true;}
 m=routeMatch(path,/^\/api\/pmo\/tasks\/([^/]+)\/dependencies$/);if(m&&req.method==='POST'){const b=await readJson(req);platform.planning.addDependency(m[0],b.dependsOnTaskId,b.type);sendJson(res,201,{status:'success'});return true;}
 return false;}catch(error){handleError(res,error);return true;}}
