export const PROJECT_STAGES = Object.freeze([
  'INQUIRY','QUALIFIED','SURVEY_SCHEDULED','SURVEY_DONE','ESTIMATING','QUOTED','NEGOTIATION','WON','DP_RECEIVED','PROCUREMENT','PRODUCTION','QC','DELIVERY_READY','INSTALLATION','HANDOVER','WARRANTY','CLOSED','ON_HOLD','LOST','CANCELLED'
]);

export const STAGE_TRANSITIONS = Object.freeze({
  INQUIRY: ['QUALIFIED','LOST','CANCELLED'],
  QUALIFIED: ['SURVEY_SCHEDULED','ESTIMATING','LOST','ON_HOLD','CANCELLED'],
  SURVEY_SCHEDULED: ['SURVEY_DONE','ON_HOLD','CANCELLED'],
  SURVEY_DONE: ['ESTIMATING','ON_HOLD','CANCELLED'],
  ESTIMATING: ['QUOTED','ON_HOLD','CANCELLED'],
  QUOTED: ['NEGOTIATION','WON','LOST','ESTIMATING','ON_HOLD'],
  NEGOTIATION: ['WON','LOST','ESTIMATING','ON_HOLD'],
  WON: ['DP_RECEIVED','ON_HOLD','CANCELLED'],
  DP_RECEIVED: ['PROCUREMENT','PRODUCTION','ON_HOLD'],
  PROCUREMENT: ['PRODUCTION','ON_HOLD'],
  PRODUCTION: ['QC','ON_HOLD'],
  QC: ['DELIVERY_READY','PRODUCTION','ON_HOLD'],
  DELIVERY_READY: ['INSTALLATION','HANDOVER','ON_HOLD'],
  INSTALLATION: ['HANDOVER','ON_HOLD'],
  HANDOVER: ['WARRANTY','CLOSED','INSTALLATION','ON_HOLD'],
  WARRANTY: ['CLOSED','ON_HOLD'],
  ON_HOLD: PROJECT_STAGES.filter((s) => !['CLOSED','LOST','CANCELLED','ON_HOLD'].includes(s)),
  CLOSED: [], LOST: [], CANCELLED: []
});

export const TASK_STATUSES = Object.freeze(['TODO','READY','IN_PROGRESS','BLOCKED','REVIEW','DONE','CANCELLED']);
export const PRIORITIES = Object.freeze(['LOW','NORMAL','HIGH','URGENT']);
export const RISK_LEVELS = Object.freeze(['LOW','MEDIUM','HIGH','CRITICAL']);
export const APPROVAL_STATUSES = Object.freeze(['PENDING','APPROVED','REJECTED','CANCELLED']);
export const APPROVAL_KINDS = Object.freeze(['INTERNAL_ESTIMATE','CUSTOMER_QUOTE','DISCOUNT','MATERIAL_PURCHASE','CHANGE_ORDER','QC_RELEASE','HANDOVER','REFUND']);
export const PAYMENT_TYPES = Object.freeze(['DP','PROGRESS','PELUNASAN','REFUND','OTHER']);
export const PAYMENT_STATUSES = Object.freeze(['PENDING','PAID','PARTIAL','OVERDUE','VOID']);
export const PROCUREMENT_STATUSES = Object.freeze(['DRAFT','REQUESTED','APPROVED','ORDERED','PARTIAL','RECEIVED','CANCELLED']);
export const PRODUCTION_STATUSES = Object.freeze(['PLANNED','READY','IN_PROGRESS','PAUSED','QC','DONE','CANCELLED']);
export const QC_STATUSES = Object.freeze(['PENDING','PASS','FAIL','REWORK']);
export const INSTALLATION_STATUSES = Object.freeze(['PLANNED','CONFIRMED','ON_SITE','BLOCKED','DONE','CANCELLED']);
export const AUTONOMY_LEVELS = Object.freeze(['MANUAL','ASSIST','SUPERVISED','AUTONOMOUS']);
export const ACTOR_TYPES = Object.freeze(['HUMAN','AGENT','SYSTEM','INTEGRATION']);
