import crypto from 'node:crypto'; import { ValidationError } from '../core/errors.mjs'; import { normalizePhone } from '../core/utils.mjs';
export class WhatsAppGateway {
 constructor({baseUrl=process.env.WA_GATEWAY_BASE_URL||'',token=process.env.WA_GATEWAY_TOKEN||'',sendPath=process.env.WA_GATEWAY_SEND_PATH||'/api/send-message',healthPath=process.env.WA_GATEWAY_HEALTH_PATH||'/health',webhookSecret=process.env.WA_GATEWAY_WEBHOOK_SECRET||'',fetchFn=globalThis.fetch}={}){this.baseUrl=baseUrl.replace(/\/$/,'');this.token=token;this.sendPath=sendPath;this.healthPath=healthPath;this.webhookSecret=webhookSecret;this.fetchFn=fetchFn;}
 configured(){return Boolean(this.baseUrl);}
 verifyWebhook(headers={}){if(!this.webhookSecret) return false;const supplied=headers['x-wa-webhook-secret']||headers['x-webhook-secret']||headers.get?.('x-wa-webhook-secret');if(!supplied)return false;const a=Buffer.from(String(supplied)),b=Buffer.from(this.webhookSecret);return a.length===b.length&&crypto.timingSafeEqual(a,b);}
 normalizeInbound(payload={}){const data=payload.data||payload.message||payload;return {externalId:String(data.id||data.messageId||payload.id||''),phone:normalizePhone(data.from||data.phone||data.sender||data.remoteJid||''),text:String(data.text||data.body||data.message?.conversation||''),name:data.pushName||data.name||null,timestamp:data.timestamp||payload.timestamp||Date.now(),raw:payload};}
 async sendText({phone,message,metadata={}}){if(!this.configured())throw new ValidationError('WA_GATEWAY_BASE_URL is not configured');if(!phone||!message)throw new ValidationError('phone and message are required');const body={phone:normalizePhone(phone),message,...metadata};const res=await this.fetchFn(`${this.baseUrl}${this.sendPath}`,{method:'POST',headers:{'content-type':'application/json',...(this.token?{authorization:`Bearer ${this.token}`,'x-api-key':this.token}:{})},body:JSON.stringify(body)});const text=await res.text();let payload;try{payload=JSON.parse(text);}catch{payload={raw:text};}if(!res.ok)throw new Error(`WA gateway ${res.status}: ${text.slice(0,300)}`);return {ok:true,status:res.status,payload};}
 async health(){if(!this.configured())return {configured:false,ok:false};try{const res=await this.fetchFn(`${this.baseUrl}${this.healthPath}`,{headers:this.token?{authorization:`Bearer ${this.token}`}:{}});return {configured:true,ok:res.ok,status:res.status};}catch(error){return {configured:true,ok:false,error:error.message};}}
}
