import { uid,nowIso,money } from '../core/utils.mjs'; import { PAYMENT_TYPES,PAYMENT_STATUSES } from '../core/constants.mjs'; import { requireFields,assertEnum } from '../core/validation.mjs'; import { NotFoundError } from '../core/errors.mjs';
export class FinanceService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 addPayment(projectId,input){requireFields(input,['type','amount']);assertEnum(input.type,PAYMENT_TYPES,'payment type');const status=input.status||'PENDING';assertEnum(status,PAYMENT_STATUSES,'payment status');const id=uid('pay'),ts=nowIso();this.db.prepare(`INSERT INTO payments(id,project_id,type,status,amount,due_date,paid_at,method,reference,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.type,status,money(input.amount),input.dueDate||null,input.paidAt||null,input.method||null,input.reference||null,input.note||null,ts,ts);return this.getPayment(id);}
 markPaid(id,input={}){const p=this.getPayment(id);if(!p)throw new NotFoundError('PAYMENT_NOT_FOUND');const ts=input.paidAt||nowIso();this.db.prepare(`UPDATE payments SET status='PAID',paid_at=?,method=?,reference=?,updated_at=? WHERE id=?`).run(ts,input.method||p.method,input.reference||p.reference,nowIso(),id);if(p.type==='DP')this.db.prepare(`UPDATE projects SET deposit_paid=deposit_paid+?,updated_at=? WHERE id=?`).run(p.amount,nowIso(),p.project_id);this.activity?.add({projectId:p.project_id,eventType:'PAYMENT_PAID',title:`${p.type} payment received`,body:String(p.amount)});return this.getPayment(id);}
 addCost(projectId,input){requireFields(input,['category','amount']);const id=uid('cost');this.db.prepare(`INSERT INTO cost_entries(id,project_id,category,amount,vendor,reference,incurred_at,note,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.category,money(input.amount),input.vendor||null,input.reference||null,input.incurredAt||nowIso(),input.note||null,JSON.stringify(input.metadata||{}),nowIso());return this.db.prepare(`SELECT * FROM cost_entries WHERE id=?`).get(id);}
 upsertBudget(projectId,category,input){const ts=nowIso();this.db.prepare(`INSERT INTO budgets(id,project_id,category,planned,committed,actual,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(project_id,category) DO UPDATE SET planned=excluded.planned,committed=excluded.committed,actual=excluded.actual,updated_at=excluded.updated_at`).run(uid('bud'),projectId,category,money(input.planned),money(input.committed),money(input.actual),ts);return this.db.prepare(`SELECT * FROM budgets WHERE project_id=? AND category=?`).get(projectId,category);}
 getPayment(id){return this.db.prepare(`SELECT * FROM payments WHERE id=?`).get(id)||null;}
 summary(projectId){const contract=Number(this.db.prepare(`SELECT contract_value v FROM projects WHERE id=?`).get(projectId)?.v||0);const paid=Number(this.db.prepare(`SELECT COALESCE(SUM(amount),0) v FROM payments WHERE project_id=? AND status='PAID'`).get(projectId)?.v||0);const costs=Number(this.db.prepare(`SELECT COALESCE(SUM(amount),0) v FROM cost_entries WHERE project_id=?`).get(projectId)?.v||0);return {contractValue:contract,paid,outstanding:money(contract-paid),costs,grossMargin:money(contract-costs),grossMarginPercent:contract?money((contract-costs)/contract*100):0};}
}
