import { uid,nowIso,jsonStringify } from '../core/utils.mjs'; import { RISK_LEVELS,APPROVAL_KINDS,APPROVAL_STATUSES } from '../core/constants.mjs'; import { requireFields,assertEnum } from '../core/validation.mjs'; import { NotFoundError } from '../core/errors.mjs';
export class GovernanceService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 addRisk(projectId,input){requireFields(input,['title']);const id=uid('risk'),ts=nowIso(),sev=input.severity||this.scoreSeverity(input.probability,input.impact);assertEnum(sev,RISK_LEVELS,'risk severity');this.db.prepare(`INSERT INTO risks(id,project_id,title,description,probability,impact,severity,status,owner,mitigation,contingency,due_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.title,input.description||null,Number(input.probability)||0.5,Number(input.impact)||0.5,sev,'OPEN',input.owner||null,input.mitigation||null,input.contingency||null,input.dueDate||null,ts,ts);return this.db.prepare(`SELECT * FROM risks WHERE id=?`).get(id);}
 scoreSeverity(prob=.5,impact=.5){const s=Number(prob)*Number(impact);return s>=.75?'CRITICAL':s>=.5?'HIGH':s>=.25?'MEDIUM':'LOW';}
 addIssue(projectId,input){requireFields(input,['title']);const id=uid('issue'),ts=nowIso(),sev=input.severity||'MEDIUM';assertEnum(sev,RISK_LEVELS,'issue severity');this.db.prepare(`INSERT INTO issues(id,project_id,title,description,severity,status,owner,due_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.title,input.description||null,sev,'OPEN',input.owner||null,input.dueDate||null,ts,ts);return this.db.prepare(`SELECT * FROM issues WHERE id=?`).get(id);}
 requestDecision(projectId,input){requireFields(input,['title']);const id=uid('dec'),ts=nowIso();this.db.prepare(`INSERT INTO decisions(id,project_id,title,context,options_json,status,requested_from,due_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.title,input.context||null,jsonStringify(input.options||[]),'OPEN',input.requestedFrom||null,input.dueDate||null,ts,ts);return this.db.prepare(`SELECT * FROM decisions WHERE id=?`).get(id);}
 decide(id,input){const d=this.db.prepare(`SELECT * FROM decisions WHERE id=?`).get(id);if(!d)throw new NotFoundError('DECISION_NOT_FOUND');const ts=nowIso();this.db.prepare(`UPDATE decisions SET decision=?,rationale=?,status='DECIDED',decided_by=?,decided_at=?,updated_at=? WHERE id=?`).run(input.decision,input.rationale||null,input.decidedBy||'boss',ts,ts,id);return this.db.prepare(`SELECT * FROM decisions WHERE id=?`).get(id);}
 requestApproval(projectId,input){requireFields(input,['kind','subject']);assertEnum(input.kind,APPROVAL_KINDS,'approval kind');const id=uid('apr'),ts=nowIso();this.db.prepare(`INSERT INTO approvals(id,project_id,kind,status,amount,subject,payload_json,requested_by,requested_from,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.kind,'PENDING',input.amount==null?null:Number(input.amount),input.subject,jsonStringify(input.payload),input.requestedBy||null,input.requestedFrom||'boss',ts);return this.db.prepare(`SELECT * FROM approvals WHERE id=?`).get(id);}
 decideApproval(id,status,input={}){assertEnum(status,APPROVAL_STATUSES,'approval status');const a=this.db.prepare(`SELECT * FROM approvals WHERE id=?`).get(id);if(!a)throw new NotFoundError('APPROVAL_NOT_FOUND');const ts=nowIso();this.db.prepare(`UPDATE approvals SET status=?,decided_by=?,decision_note=?,decided_at=? WHERE id=?`).run(status,input.decidedBy||'boss',input.note||null,ts,id);this.activity?.add({projectId:a.project_id,eventType:'APPROVAL_DECIDED',title:`${a.kind}: ${status}`,actor:input.decidedBy||'boss'});return this.db.prepare(`SELECT * FROM approvals WHERE id=?`).get(id);}
 pendingApprovals(limit=100){return this.db.prepare(`SELECT * FROM approvals WHERE status='PENDING' ORDER BY created_at LIMIT ?`).all(Math.min(500,Number(limit)||100));}
}
