import { uid,nowIso,jsonStringify,jsonParse } from '../core/utils.mjs'; import { NotFoundError } from '../core/errors.mjs'; import { classifyInboxText,extractLeadFacts } from '../ai/inbox_classifier.mjs';
export class InboxService {constructor(db,{projects,messages}={}){this.db=db.db||db;this.projects=projects;this.messages=messages;}
 ingestMessage(message,{name=null}={}){const existing=this.db.prepare(`SELECT * FROM inbox_items WHERE message_id=?`).get(message.id);if(existing)return this._map(existing);const c=classifyInboxText(message.text),id=uid('inb'),ts=nowIso(),facts=extractLeadFacts(message.text);this.db.prepare(`INSERT INTO inbox_items(id,message_id,phone,contact_name,classification,confidence,status,project_id,summary,extracted_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,message.id,message.phone,name,c.classification,c.confidence,message.project_id?'LINKED':'NEW',message.project_id,message.text?.slice(0,240)||'',jsonStringify(facts),ts,ts);return this.get(id);}
 get(id){return this._map(this.db.prepare(`SELECT * FROM inbox_items WHERE id=?`).get(id));}
 list({status='NEW',limit=100}={}){const where=status?'WHERE status=?':'';const args=status?[status,Math.min(500,Number(limit)||100)]:[Math.min(500,Number(limit)||100)];return this.db.prepare(`SELECT * FROM inbox_items ${where} ORDER BY created_at DESC LIMIT ?`).all(...args).map((r)=>this._map(r));}
 assign(id,user){this.db.prepare(`UPDATE inbox_items SET assigned_to=?,status=CASE WHEN status='NEW' THEN 'TRIAGED' ELSE status END,updated_at=? WHERE id=?`).run(user,nowIso(),id);return this.get(id);}
 promote(id,input={},opts={}){const item=this.get(id);if(!item)throw new NotFoundError('INBOX_ITEM_NOT_FOUND');let project=item.project_id?this.projects.get(item.project_id):null;if(!project)project=this.projects.create({title:input.title||`${item.contact_name||item.phone} - Custom Furniture`,clientName:input.clientName||item.contact_name,clientPhone:item.phone,siteAddress:input.siteAddress,source:'WHATSAPP',scope:input.scope||item.summary,owner:input.owner,priority:input.priority||'NORMAL'},opts);this.db.prepare(`UPDATE inbox_items SET project_id=?,status='PROMOTED',updated_at=? WHERE id=?`).run(project.id,nowIso(),id);this.db.prepare(`UPDATE messages SET project_id=? WHERE id=?`).run(project.id,item.message_id);return project;}
 _map(r){return r?{...r,extracted:jsonParse(r.extracted_json,{})}:null;}
}
