import { uid, nowIso, jsonStringify } from '../core/utils.mjs'; import { TASK_STATUSES, PRIORITIES } from '../core/constants.mjs'; import { requireFields, assertEnum } from '../core/validation.mjs'; import { NotFoundError, ConflictError } from '../core/errors.mjs';
export class PlanningService { constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 addMilestone(projectId,input){ requireFields(input,['title']); const id=uid('ms'); const ts=nowIso(); this.db.prepare(`INSERT INTO milestones(id,project_id,title,status,due_date,weight,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.title,input.status||'OPEN',input.dueDate||null,Number(input.weight)||0,Number(input.sortOrder)||0,ts,ts); this.activity?.add({projectId,eventType:'MILESTONE_CREATED',title:input.title}); return this.getMilestone(id); }
 getMilestone(id){return this.db.prepare(`SELECT * FROM milestones WHERE id=?`).get(id)||null;}
 listMilestones(projectId){return this.db.prepare(`SELECT * FROM milestones WHERE project_id=? ORDER BY sort_order,due_date`).all(projectId);}
 addTask(projectId,input){ requireFields(input,['title']); const status=input.status||'TODO'; const priority=input.priority||'NORMAL'; assertEnum(status,TASK_STATUSES,'status'); assertEnum(priority,PRIORITIES,'priority'); const id=uid('tsk'),ts=nowIso(); this.db.prepare(`INSERT INTO tasks(id,project_id,milestone_id,parent_task_id,title,description,status,priority,owner_type,owner_id,due_date,estimated_hours,progress,autonomy_level,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.milestoneId||null,input.parentTaskId||null,input.title,input.description||null,status,priority,input.ownerType||null,input.ownerId||null,input.dueDate||null,Number(input.estimatedHours)||0,Number(input.progress)||0,input.autonomyLevel||null,jsonStringify(input.metadata),ts,ts); this.activity?.add({projectId,eventType:'TASK_CREATED',title:input.title}); return this.getTask(id); }
 getTask(id){return this.db.prepare(`SELECT * FROM tasks WHERE id=?`).get(id)||null;}
 listTasks(projectId){return this.db.prepare(`SELECT * FROM tasks WHERE project_id=? ORDER BY CASE status WHEN 'BLOCKED' THEN 0 WHEN 'IN_PROGRESS' THEN 1 ELSE 2 END, due_date`).all(projectId);}
 setTaskStatus(id,status,{progress=null}={}){assertEnum(status,TASK_STATUSES,'status'); const t=this.getTask(id);if(!t)throw new NotFoundError('TASK_NOT_FOUND'); const p=progress==null?(status==='DONE'?100:t.progress):Math.max(0,Math.min(100,Number(progress)||0));this.db.prepare(`UPDATE tasks SET status=?,progress=?,updated_at=? WHERE id=?`).run(status,p,nowIso(),id);return this.getTask(id);}
 addDependency(taskId,dependsOnTaskId,type='FINISH_TO_START'){if(taskId===dependsOnTaskId) throw new ConflictError('Task cannot depend on itself');this.db.prepare(`INSERT OR IGNORE INTO task_dependencies(task_id,depends_on_task_id,dependency_type,created_at) VALUES(?,?,?,?)`).run(taskId,dependsOnTaskId,type,nowIso());return true;}
 blockers(taskId){return this.db.prepare(`SELECT t.* FROM task_dependencies d JOIN tasks t ON t.id=d.depends_on_task_id WHERE d.task_id=? AND t.status!='DONE'`).all(taskId);}
}
