import { uid,nowIso,money } from '../core/utils.mjs'; import { PROCUREMENT_STATUSES } from '../core/constants.mjs'; import { requireFields,assertEnum } from '../core/validation.mjs'; import { NotFoundError } from '../core/errors.mjs';
export class ProcurementService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 addSupplier(input){requireFields(input,['name']);const id=uid('sup'),ts=nowIso();this.db.prepare(`INSERT INTO suppliers(id,name,phone,email,address,category,rating,active,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.name,input.phone||null,input.email||null,input.address||null,input.category||null,Number(input.rating)||0,input.active===false?0:1,input.notes||null,ts,ts);return this.db.prepare(`SELECT * FROM suppliers WHERE id=?`).get(id);}
 addMaterial(input){requireFields(input,['name']);const id=uid('mat'),ts=nowIso();this.db.prepare(`INSERT INTO materials(id,sku,name,category,unit,default_supplier_id,standard_cost,min_stock,current_stock,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.sku||null,input.name,input.category||null,input.unit||'pcs',input.defaultSupplierId||null,money(input.standardCost),Number(input.minStock)||0,Number(input.currentStock)||0,JSON.stringify(input.metadata||{}),ts,ts);return this.db.prepare(`SELECT * FROM materials WHERE id=?`).get(id);}
 createRequest(projectId,input={}){const id=uid('pr'),ts=nowIso(),code=input.code||`PR-${Date.now()}`;this.db.prepare(`INSERT INTO purchase_requests(id,project_id,code,status,requested_by,needed_by,note,total_estimate,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,code,'DRAFT',input.requestedBy||null,input.neededBy||null,input.note||null,0,ts,ts);return this.getRequest(id);}
 addRequestItem(requestId,input){requireFields(input,['description','qty']);const req=this.getRequest(requestId);if(!req)throw new NotFoundError('PURCHASE_REQUEST_NOT_FOUND');const id=uid('pri');this.db.prepare(`INSERT INTO purchase_request_items(id,request_id,material_id,description,qty,unit,target_unit_cost,actual_unit_cost,supplier_id,status) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,requestId,input.materialId||null,input.description,Number(input.qty)||1,input.unit||'pcs',money(input.targetUnitCost),0,input.supplierId||null,'PENDING');this.recalculateRequest(requestId);return this.db.prepare(`SELECT * FROM purchase_request_items WHERE id=?`).get(id);}
 recalculateRequest(id){const total=Number(this.db.prepare(`SELECT COALESCE(SUM(qty*target_unit_cost),0) t FROM purchase_request_items WHERE request_id=?`).get(id).t||0);this.db.prepare(`UPDATE purchase_requests SET total_estimate=?,updated_at=? WHERE id=?`).run(money(total),nowIso(),id);return this.getRequest(id);}
 setRequestStatus(id,status){assertEnum(status,PROCUREMENT_STATUSES,'procurement status');this.db.prepare(`UPDATE purchase_requests SET status=?,updated_at=? WHERE id=?`).run(status,nowIso(),id);return this.getRequest(id);}
 createPO(projectId,input){requireFields(input,['supplierId']);const id=uid('po'),ts=nowIso(),poNo=input.poNo||`PO-${Date.now()}`;this.db.prepare(`INSERT INTO purchase_orders(id,project_id,request_id,supplier_id,po_no,status,subtotal,tax,shipping,grand_total,ordered_at,expected_at,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.requestId||null,input.supplierId,poNo,input.status||'DRAFT',money(input.subtotal),money(input.tax),money(input.shipping),money((input.subtotal||0)+(input.tax||0)+(input.shipping||0)),input.orderedAt||null,input.expectedAt||null,input.note||null,ts,ts);return this.db.prepare(`SELECT * FROM purchase_orders WHERE id=?`).get(id);}
 getRequest(id){return this.db.prepare(`SELECT * FROM purchase_requests WHERE id=?`).get(id)||null;}
 listRequests(projectId){return this.db.prepare(`SELECT * FROM purchase_requests WHERE project_id=? ORDER BY created_at DESC`).all(projectId);}
}
