import { uid,nowIso } from '../core/utils.mjs'; import { PRODUCTION_STATUSES } from '../core/constants.mjs'; import { requireFields,assertEnum } from '../core/validation.mjs'; import { NotFoundError } from '../core/errors.mjs';
export class ProductionService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 createJob(projectId,input){requireFields(input,['title']);const id=uid('job'),ts=nowIso(),code=input.code||`JOB-${Date.now()}`;this.db.prepare(`INSERT INTO production_jobs(id,project_id,code,title,status,workstation,supervisor,planned_start,planned_finish,progress,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,code,input.title,'PLANNED',input.workstation||null,input.supervisor||null,input.plannedStart||null,input.plannedFinish||null,0,input.notes||null,ts,ts);this.activity?.add({projectId,eventType:'PRODUCTION_JOB_CREATED',title:input.title});return this.getJob(id);}
 addStep(jobId,input){requireFields(input,['name']);const job=this.getJob(jobId);if(!job)throw new NotFoundError('PRODUCTION_JOB_NOT_FOUND');const id=uid('step');this.db.prepare(`INSERT INTO production_steps(id,job_id,name,sequence,status,assignee,planned_minutes,actual_minutes,checklist_json,notes) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,jobId,input.name,Number(input.sequence)||0,'TODO',input.assignee||null,Number(input.plannedMinutes)||0,0,JSON.stringify(input.checklist||[]),input.notes||null);return this.db.prepare(`SELECT * FROM production_steps WHERE id=?`).get(id);}
 setJobStatus(id,status){assertEnum(status,PRODUCTION_STATUSES,'production status');const job=this.getJob(id);if(!job)throw new NotFoundError('PRODUCTION_JOB_NOT_FOUND');const ts=nowIso();const start=status==='IN_PROGRESS'&&!job.actual_start?ts:job.actual_start;const finish=status==='DONE'?ts:job.actual_finish;const progress=status==='DONE'?100:job.progress;this.db.prepare(`UPDATE production_jobs SET status=?,actual_start=?,actual_finish=?,progress=?,updated_at=? WHERE id=?`).run(status,start,finish,progress,ts,id);return this.getJob(id);}
 completeStep(id,{actualMinutes=0,notes=null}={}){const s=this.db.prepare(`SELECT ps.*,pj.project_id FROM production_steps ps JOIN production_jobs pj ON pj.id=ps.job_id WHERE ps.id=?`).get(id);if(!s)throw new NotFoundError('PRODUCTION_STEP_NOT_FOUND');this.db.prepare(`UPDATE production_steps SET status='DONE',actual_minutes=?,completed_at=?,notes=COALESCE(?,notes) WHERE id=?`).run(Number(actualMinutes)||0,nowIso(),notes,id);this.refreshProgress(s.job_id);return this.db.prepare(`SELECT * FROM production_steps WHERE id=?`).get(id);}
 refreshProgress(jobId){const r=this.db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='DONE' THEN 1 ELSE 0 END) done FROM production_steps WHERE job_id=?`).get(jobId);const progress=r.total?Math.round((r.done/r.total)*100):0;this.db.prepare(`UPDATE production_jobs SET progress=?,updated_at=? WHERE id=?`).run(progress,nowIso(),jobId);return progress;}
 getJob(id){return this.db.prepare(`SELECT * FROM production_jobs WHERE id=?`).get(id)||null;}
 listJobs(projectId){return this.db.prepare(`SELECT * FROM production_jobs WHERE project_id=? ORDER BY created_at DESC`).all(projectId);}
}
