import { PROJECT_STAGES, STAGE_TRANSITIONS, PRIORITIES } from '../core/constants.mjs';
import { ConflictError, NotFoundError, ValidationError } from '../core/errors.mjs';
import { nowIso, uid, normalizePhone, jsonStringify, jsonParse, money } from '../core/utils.mjs';
import { requireFields, assertEnum } from '../core/validation.mjs';
export class ProjectService {
 constructor(db,{audit,activity}={}){ this.db=db.db||db; this.audit=audit; this.activity=activity; }
 create(input,{actor={type:'HUMAN',id:'boss'}}={}){ requireFields(input,['title']); const id=input.id||uid('prj'); const ts=nowIso(); const code=input.code||this._nextCode(); const stage=input.stage||'INQUIRY'; assertEnum(stage,PROJECT_STAGES,'stage'); const priority=input.priority||'NORMAL'; assertEnum(priority,PRIORITIES,'priority');
  this.db.prepare(`INSERT INTO projects(id,code,title,stage,client_name,client_phone,client_email,site_address,source,scope,material_spec,finish_spec,estimated_value,quoted_value,contract_value,deposit_required,deposit_paid,owner,priority,start_date,due_date,metadata_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,code,String(input.title).trim(),stage,input.clientName||null,normalizePhone(input.clientPhone||''),input.clientEmail||null,input.siteAddress||null,input.source||'MANUAL',input.scope||null,input.materialSpec||null,input.finishSpec||null,money(input.estimatedValue),money(input.quotedValue),money(input.contractValue),money(input.depositRequired),money(input.depositPaid),input.owner||null,priority,input.startDate||null,input.dueDate||null,jsonStringify(input.metadata),ts,ts);
  const project=this.get(id); this.audit?.record({entityType:'project',entityId:id,action:'CREATE',actor,after:project}); this.activity?.add({projectId:id,eventType:'PROJECT_CREATED',title:`Project ${code} created`,actor:actor.id}); return project; }
 _nextCode(){ const y=new Date().getFullYear(); const row=this.db.prepare(`SELECT COUNT(*) c FROM projects WHERE code LIKE ?`).get(`PRJ-${y}-%`); return `PRJ-${y}-${String((row?.c||0)+1).padStart(4,'0')}`; }
 get(id){ const r=this.db.prepare(`SELECT * FROM projects WHERE id=? OR code=?`).get(id,id); return this._map(r); }
 findByPhone(phone){ const p=normalizePhone(phone); const r=this.db.prepare(`SELECT * FROM projects WHERE client_phone=? ORDER BY updated_at DESC LIMIT 1`).get(p); return this._map(r); }
 list({stage=null,limit=100,search=null}={}){ const clauses=[]; const p=[]; if(stage){clauses.push('stage=?');p.push(stage);} if(search){clauses.push('(title LIKE ? OR code LIKE ? OR client_name LIKE ?)'); const q=`%${search}%`; p.push(q,q,q);} p.push(Math.min(500,Number(limit)||100)); return this.db.prepare(`SELECT * FROM projects ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY updated_at DESC LIMIT ?`).all(...p).map((r)=>this._map(r)); }
 update(id,patch,{actor={type:'HUMAN',id:'boss'}}={}){ const before=this.get(id); if(!before) throw new NotFoundError('PROJECT_NOT_FOUND'); const map={title:'title',clientName:'client_name',clientPhone:'client_phone',clientEmail:'client_email',siteAddress:'site_address',source:'source',scope:'scope',materialSpec:'material_spec',finishSpec:'finish_spec',estimatedValue:'estimated_value',quotedValue:'quoted_value',contractValue:'contract_value',depositRequired:'deposit_required',depositPaid:'deposit_paid',owner:'owner',priority:'priority',startDate:'start_date',dueDate:'due_date',metadata:'metadata_json'}; const sets=[]; const vals=[]; for(const [k,col] of Object.entries(map)){ if(!(k in patch)) continue; let v=patch[k]; if(k==='clientPhone') v=normalizePhone(v); if(['estimatedValue','quotedValue','contractValue','depositRequired','depositPaid'].includes(k)) v=money(v); if(k==='metadata') v=jsonStringify(v); if(k==='priority') assertEnum(v,PRIORITIES,'priority'); sets.push(`${col}=?`); vals.push(v); } if(!sets.length) return before; sets.push('updated_at=?'); vals.push(nowIso(),before.id); this.db.prepare(`UPDATE projects SET ${sets.join(',')} WHERE id=?`).run(...vals); const after=this.get(before.id); this.audit?.record({entityType:'project',entityId:before.id,action:'UPDATE',actor,before,after}); this.activity?.add({projectId:before.id,eventType:'PROJECT_UPDATED',title:'Project updated',actor:actor.id,payload:{fields:Object.keys(patch)}}); return after; }
 transition(id,toStage,{actor={type:'HUMAN',id:'boss'},note=null,force=false}={}){ const before=this.get(id); if(!before) throw new NotFoundError('PROJECT_NOT_FOUND'); assertEnum(toStage,PROJECT_STAGES,'stage'); if(!force && !(STAGE_TRANSITIONS[before.stage]||[]).includes(toStage)) throw new ConflictError(`Invalid stage transition ${before.stage} -> ${toStage}`); const ts=nowIso(); const won=toStage==='WON'?ts:before.won_at; const closed=toStage==='CLOSED'?ts:before.closed_at; this.db.prepare(`UPDATE projects SET stage=?,won_at=?,closed_at=?,updated_at=? WHERE id=?`).run(toStage,won,closed,ts,before.id); const after=this.get(before.id); this.audit?.record({entityType:'project',entityId:before.id,action:'STAGE_TRANSITION',actor,before,after,metadata:{note}}); this.activity?.add({projectId:before.id,eventType:'STAGE_CHANGED',title:`${before.stage} → ${toStage}`,body:note,actor:actor.id}); return after; }
 _map(r){ if(!r) return null; return {...r,clientName:r.client_name,clientPhone:r.client_phone,clientEmail:r.client_email,siteAddress:r.site_address,materialSpec:r.material_spec,finishSpec:r.finish_spec,estimatedValue:r.estimated_value,quotedValue:r.quoted_value,contractValue:r.contract_value,depositRequired:r.deposit_required,depositPaid:r.deposit_paid,startDate:r.start_date,dueDate:r.due_date,metadata:jsonParse(r.metadata_json,{})}; }
}
