import { uid,nowIso,jsonStringify } from '../core/utils.mjs'; import { QC_STATUSES } from '../core/constants.mjs'; import { requireFields,assertEnum } from '../core/validation.mjs'; import { NotFoundError,ConflictError } from '../core/errors.mjs';
export const DEFAULT_WOOD_QC=[['dimension','Dimensi sesuai gambar kerja'],['material','Jenis dan ketebalan material sesuai'],['joinery','Sambungan kuat dan rapi'],['surface','Permukaan bebas cacat'],['edge','Edge banding/list rapi'],['finish','Warna dan finishing sesuai sample'],['hardware','Hardware lengkap dan berfungsi'],['alignment','Pintu/laci/alignment presisi'],['packaging','Packaging aman untuk pengiriman']];
export class QualityService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 createInspection(projectId,input={}){const id=uid('qc'),ts=nowIso();this.db.prepare(`INSERT INTO qc_inspections(id,project_id,production_job_id,type,status,inspector,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`).run(id,projectId,input.productionJobId||null,input.type||'FINAL','PENDING',input.inspector||null,ts,ts);const items=input.items||DEFAULT_WOOD_QC;for(const x of items){const [key,label]=Array.isArray(x)?x:[x.key,x.label];this.db.prepare(`INSERT INTO qc_items(id,inspection_id,item_key,label,required,status) VALUES(?,?,?,?,?,?)`).run(uid('qci'),id,key,label,1,'PENDING');}return this.get(id);}
 setItem(itemId,status,note=null,evidence=[]){assertEnum(status,QC_STATUSES,'qc status');this.db.prepare(`UPDATE qc_items SET status=?,note=?,evidence_json=? WHERE id=?`).run(status,note,jsonStringify(evidence),itemId);return this.db.prepare(`SELECT * FROM qc_items WHERE id=?`).get(itemId);}
 finalize(id,{inspector=null,notes=null}={}){const inspection=this.get(id);if(!inspection)throw new NotFoundError('QC_NOT_FOUND');const items=this.items(id);const failed=items.filter((x)=>x.required && x.status!=='PASS');if(failed.length)throw new ConflictError('QC cannot pass while required checklist items are not PASS',{failed:failed.map((x)=>x.item_key)});const ts=nowIso();this.db.prepare(`UPDATE qc_inspections SET status='PASS',inspector=COALESCE(?,inspector),inspected_at=?,score=100,notes=?,updated_at=? WHERE id=?`).run(inspector,ts,notes,ts,id);this.activity?.add({projectId:inspection.project_id,eventType:'QC_PASSED',title:'Quality control passed'});return this.get(id);}
 get(id){return this.db.prepare(`SELECT * FROM qc_inspections WHERE id=?`).get(id)||null;}
 items(id){return this.db.prepare(`SELECT * FROM qc_items WHERE inspection_id=? ORDER BY rowid`).all(id);}
}
