import { uid,nowIso,money } from '../core/utils.mjs'; import { requireFields } from '../core/validation.mjs'; import { NotFoundError } from '../core/errors.mjs';
export class QuoteService {constructor(db,{activity}={}){this.db=db.db||db;this.activity=activity;}
 create(projectId,input={}){const id=uid('qte'),ts=nowIso();const ver=(this.db.prepare(`SELECT COALESCE(MAX(version),0)+1 v FROM quotes WHERE project_id=?`).get(projectId)?.v)||1;const quoteNo=input.quoteNo||`Q-${new Date().getFullYear()}-${String(this.db.prepare(`SELECT COUNT(*) c FROM quotes`).get().c+1).padStart(5,'0')}`;this.db.prepare(`INSERT INTO quotes(id,project_id,estimate_id,quote_no,version,status,discount,valid_until,terms,customer_note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,projectId,input.estimateId||null,quoteNo,ver,'DRAFT',money(input.discount),input.validUntil||null,input.terms||null,input.customerNote||null,ts,ts);return this.get(id);}
 addItem(quoteId,input){requireFields(input,['description']);const q=this.get(quoteId);if(!q)throw new NotFoundError('QUOTE_NOT_FOUND');const qty=Number(input.qty)||1,unitPrice=money(input.unitPrice),total=money(qty*unitPrice);const id=uid('qi');this.db.prepare(`INSERT INTO quote_items(id,quote_id,description,qty,unit,unit_price,total,sort_order) VALUES(?,?,?,?,?,?,?,?)`).run(id,quoteId,input.description,qty,input.unit||'pcs',unitPrice,total,Number(input.sortOrder)||0);this.recalculate(quoteId);return this.db.prepare(`SELECT * FROM quote_items WHERE id=?`).get(id);}
 recalculate(id){const q=this.get(id);if(!q)throw new NotFoundError('QUOTE_NOT_FOUND');const subtotal=money(this.db.prepare(`SELECT COALESCE(SUM(total),0) t FROM quote_items WHERE quote_id=?`).get(id).t);const discount=money(q.discount),tax=money(inputTax(q,subtotal-discount)),grand=money(subtotal-discount+tax);this.db.prepare(`UPDATE quotes SET subtotal=?,tax=?,grand_total=?,updated_at=? WHERE id=?`).run(subtotal,tax,grand,nowIso(),id);return this.get(id);}
 markSent(id){const ts=nowIso();this.db.prepare(`UPDATE quotes SET status='SENT',sent_at=?,updated_at=? WHERE id=?`).run(ts,ts,id);const q=this.get(id);this.activity?.add({projectId:q?.project_id,eventType:'QUOTE_SENT',title:`Quote ${q?.quote_no} sent`});return q;}
 approve(id){const ts=nowIso();this.db.prepare(`UPDATE quotes SET status='APPROVED',approved_at=?,updated_at=? WHERE id=?`).run(ts,ts,id);const q=this.get(id); if(q) this.db.prepare(`UPDATE projects SET quoted_value=?,contract_value=?,updated_at=? WHERE id=?`).run(q.grand_total,q.grand_total,ts,q.project_id); return this.get(id);}
 get(id){return this.db.prepare(`SELECT * FROM quotes WHERE id=?`).get(id)||null;}
 items(id){return this.db.prepare(`SELECT * FROM quote_items WHERE quote_id=? ORDER BY sort_order,rowid`).all(id);}
}
function inputTax(q,base){const m=String(q.terms||'').match(/tax:(\d+(?:\.\d+)?)/i);return m?base*Number(m[1])/100:0;}
